### ISSUE TITLE
Short tag <?= warning is not relevant anymore

### ISSUE THREAD

**Issue by sineway** [envato/envato-theme-check#48] opened 2019-07-04 16:20 UTC
Since PHP 5.4.0 the tag <?= is always available regardless of the short_open_tag ini setting.
At the moment of writing [WordPress requires PHP 5.6.20 or greater](https://codex.wordpress.org/Template:Server_requirements).

**Comment by Stephen-Cronin** [comment] 2019-07-05 00:04
Hi, this is a duplicate of #44 so I'll copy paste that response here:

>Our current stance is that we don't allow <?=. Part of the reasoning was due to WP's PHP version (no longer an issue as you point out now that PHP5.6 is the minimum), but it was also due to confusion we've seen in the past with some authors thinking it means that <? is allowed.
>
>We may revisit this in future (ie I'll add it to the list to be considered for next time we update the requirements), but for now we don't allow it. I'll close this, as this is for the Theme Check plugin not the requirements. Thanks for raising it though.

Note: we've discussed it a little now and are like to allow it in the next version of the requirements, but it's not guaranteed yet.

**Closed** 2019-07-05 00:05 UTC

**Comment by sineway** [comment] 2019-07-05 09:57
Okay, I got it. 
Thanks for quick reply.
